### ISSUE TITLE
256-bits key

### ISSUE THREAD

**Issue by retro-desert** [bauhuasbadguy/Twofish_encryption#2]
Correctly, I understand that if you enter a 256-bit key, will there be 256-bit encryption?
P.S. I just don’t know how to contact you

**Comment by bauhuasbadguy** [comment]
Sorry, I'm not sure what you mean. From what I remember (its a while since I stopped working on this) I use 256 bit blocks when encrypting and I guess you could say it's 256 bit encryption since the key is 256 bits long

**Comment by retro-desert** [comment]
Thanks @bauhuasbadguy . I just added your code to my program and I think that you did a good job.  But the bug is really strange (random characters when decrypting)

**Comment by bauhuasbadguy** [comment]
I really would not use this code to build further projects. This was done to help me understand the encryption method of twofish and I hope it is helpful to you in that regard (even if I forgot to write a README) but if you're using twofish in a further project I would recommend using an implementation intended for public consumption. Like this one here:- https://pypi.org/project/twofish/

**Comment by retro-desert** [comment]
I tried to use this code but nothing worked
